# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'local_uiHpNcfL.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QLayout,
    QLineEdit, QListView, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QTabWidget, QTextBrowser, QToolBox, QToolButton,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(843, 636)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 841, 611))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.Main_Title = QLabel(self.page)
        self.Main_Title.setObjectName(u"Main_Title")
        self.Main_Title.setGeometry(QRect(30, 30, 631, 61))
        self.Main_ZhangHao_Input = QLineEdit(self.page)
        self.Main_ZhangHao_Input.setObjectName(u"Main_ZhangHao_Input")
        self.Main_ZhangHao_Input.setGeometry(QRect(120, 170, 221, 41))
        self.Main_ZhangHao_Input.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Main_ZhangHaoText = QLabel(self.page)
        self.Main_ZhangHaoText.setObjectName(u"Main_ZhangHaoText")
        self.Main_ZhangHaoText.setGeometry(QRect(50, 170, 53, 15))
        self.Main_PassWord_text = QLabel(self.page)
        self.Main_PassWord_text.setObjectName(u"Main_PassWord_text")
        self.Main_PassWord_text.setGeometry(QRect(50, 250, 61, 41))
        self.Main_PassWord_Input = QLineEdit(self.page)
        self.Main_PassWord_Input.setObjectName(u"Main_PassWord_Input")
        self.Main_PassWord_Input.setGeometry(QRect(120, 250, 221, 41))
        self.Main_PassWord_Input.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Main_PassWord_Input.setEchoMode(QLineEdit.EchoMode.Password)
        self.Main_Login_Button = QPushButton(self.page)
        self.Main_Login_Button.setObjectName(u"Main_Login_Button")
        self.Main_Login_Button.setGeometry(QRect(50, 360, 221, 71))
        self.Main_Login_Button.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Main_instct_Button = QPushButton(self.page)
        self.Main_instct_Button.setObjectName(u"Main_instct_Button")
        self.Main_instct_Button.setGeometry(QRect(50, 460, 75, 23))
        self.Main_instct_Button.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Main_Lost_Password = QPushButton(self.page)
        self.Main_Lost_Password.setObjectName(u"Main_Lost_Password")
        self.Main_Lost_Password.setGeometry(QRect(200, 460, 75, 23))
        self.Main_Lost_Password.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Main_OffLine_Run = QPushButton(self.page)
        self.Main_OffLine_Run.setObjectName(u"Main_OffLine_Run")
        self.Main_OffLine_Run.setGeometry(QRect(460, 160, 331, 81))
        self.Main_OffLine_Run.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.Main_Exit_Button = QPushButton(self.page)
        self.Main_Exit_Button.setObjectName(u"Main_Exit_Button")
        self.Main_Exit_Button.setGeometry(QRect(734, 552, 101, 41))
        self.Main_Exit_Button.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.remember = QCheckBox(self.page)
        self.remember.setObjectName(u"remember")
        self.remember.setGeometry(QRect(710, 250, 80, 19))
        self.remember.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.tabWidget = QTabWidget(self.page_2)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 841, 601))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.webEngineView = QWebEngineView(self.tab)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setGeometry(QRect(0, 0, 831, 571))
        self.webEngineView.setUrl(QUrl(u"about:blank"))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.listView = QListView(self.tab_2)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(0, 0, 201, 571))
        self.webEngineView_2 = QWebEngineView(self.tab_2)
        self.webEngineView_2.setObjectName(u"webEngineView_2")
        self.webEngineView_2.setGeometry(QRect(200, 0, 631, 571))
        self.webEngineView_2.setUrl(QUrl(u"about:blank"))
        self.toolButton = QToolButton(self.tab_2)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(320, 570, 24, 21))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.webEngineView_3 = QWebEngineView(self.tab_3)
        self.webEngineView_3.setObjectName(u"webEngineView_3")
        self.webEngineView_3.setGeometry(QRect(0, 0, 831, 571))
        self.webEngineView_3.setUrl(QUrl(u"about:blank"))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.webEngineView_4 = QWebEngineView(self.tab_4)
        self.webEngineView_4.setObjectName(u"webEngineView_4")
        self.webEngineView_4.setGeometry(QRect(0, 0, 831, 571))
        self.webEngineView_4.setUrl(QUrl(u"about:blank"))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.toolBox = QToolBox(self.tab_5)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(0, 0, 831, 571))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 831, 513))
        self.webEngineView_5 = QWebEngineView(self.page_3)
        self.webEngineView_5.setObjectName(u"webEngineView_5")
        self.webEngineView_5.setGeometry(QRect(0, 0, 831, 521))
        self.webEngineView_5.setUrl(QUrl(u"about:blank"))
        self.ico = QLabel(self.page_3)
        self.ico.setObjectName(u"ico")
        self.ico.setGeometry(QRect(300, 10, 271, 251))
        self.version = QLabel(self.page_3)
        self.version.setObjectName(u"version")
        self.version.setGeometry(QRect(40, 490, 771, 16))
        self.Md_Show = QTextBrowser(self.page_3)
        self.Md_Show.setObjectName(u"Md_Show")
        self.Md_Show.setGeometry(QRect(10, 170, 811, 311))
        self.Md_Show.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.WhatsThisCursor))
        self.toolBox.addItem(self.page_3, u"Page 1")
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4.setGeometry(QRect(0, 0, 98, 28))
        self.lineEdit_3 = QLineEdit(self.page_4)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(0, 0, 831, 511))
        self.toolBox.addItem(self.page_4, u"Page 2")
        self.tabWidget.addTab(self.tab_5, "")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 843, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Main_Title.setText(QCoreApplication.translate("MainWindow", u"Ne Games Luncher", None))
        self.Main_ZhangHaoText.setText(QCoreApplication.translate("MainWindow", u"\u8d26\u53f7\uff1a", None))
        self.Main_PassWord_text.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u7801", None))
        self.Main_PassWord_Input.setText("")
        self.Main_Login_Button.setText(QCoreApplication.translate("MainWindow", u"\u767b\u5f55", None))
        self.Main_instct_Button.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u518c", None))
        self.Main_Lost_Password.setText(QCoreApplication.translate("MainWindow", u"\u5fd8\u8bb0\u5bc6\u7801", None))
        self.Main_OffLine_Run.setText(QCoreApplication.translate("MainWindow", u"\u79bb\u7ebf\u8fd0\u884c", None))
        self.Main_Exit_Button.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.remember.setText(QCoreApplication.translate("MainWindow", u"\u8bb0\u4f4f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u9875", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u9875", None))
        self.ico.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.version.setText(QCoreApplication.translate("MainWindow", u"version", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("MainWindow", u"Page 1", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QCoreApplication.translate("MainWindow", u"Page 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u9875", None))
    # retranslateUi

